[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "20"

[context.deploy-preview]
  command = "npm run build && npm start"
  NODE_VERSION = "20"
